### PR TITLE
feat: windows support

### PR DESCRIPTION
**Pull request by jinzhongjia**
This PR is used to add windows support, but do not merge it yet.
The PR still needs more testing

### CODE REVIEW

**Comment by jinzhongjia** [comment]
I noticed that page_allocator is used extensively in the overall code. This memory allocator will directly allocate the entire page, and its speed is slower.

Now I created a new file called `tool.zig`, which stores an allocator. Maybe we can use gpa

**Comment by jinzhongjia** [comment]
And I adjusted the build mode in `build.zig` to default, which will speed up compilation on windows and facilitate debugging.

**Comment by jinzhongjia** [comment]
I also found that the use of `std.debug.print` seems a bit excessive. Zig officially recommends using `std.log` to achieve this

**Comment by jinzhongjia** [comment]
and tested the following latest released zvm under my wsl2, it seems to have some issues
image

**Comment by jinzhongjia** [comment]
But it seems that they are all executed successfully, and further investigation may be needed.

**Comment by jinzhongjia** [comment]
Oh, I see that most of the situations above have been mentioned by you in other issues

**Comment by hendriknielaender** [comment]
> Oh, I see that most of the situations above have been mentioned by you in other issues

Yeah, if there is something not yet covered feel free to open up an issue.

> I also found that the use of std.debug.print seems a bit excessive. Zig officially recommends using std.log to achieve this

For not getting this PR too big. You can open up a pull request for these improvements or like i mentioned open up an issue.

Overall looking great, really appreciate your contribution. Ping me if you think it should be reviewed.

**Comment by jinzhongjia** [comment]
Then if you think there is no problem, I have done some tests and it seems that we can temporarily merge the PR.

**Comment by jinzhongjia** [comment]
Regarding other issues, I will open a new PR separately.

**Review by hendriknielaender — COMMENTED** [review]
Looks good to me! Great work.

**Comment by jinzhongjia** [comment]
The current code can only be said to work, after the PR is merged, I will reorganize the code logic, including fixes for issues that have been raised

**Comment by jinzhongjia** [comment]
Later we can try to apply for administrator rights when needed. The speed of copying files on the Windows platform is really not ideal.

**Pull request merged**
